# Postgres 9.3.0.0
#
development:
  adapter: postgresql
  encoding: unicode
  database: bev_dev
  pool: 5
  timeout: 5000
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: bev_test
  pool: 5
  timeout: 5000
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: bev_prod
  pool: 5
  timeout: 5000
